services:
  nginx:
    image: nginx:1.29
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ../www:/var/www/html
      - ./nginx:/etc/nginx/conf.d:ro
    depends_on:
      - php83
      - node20

  php83:
    build:
      context: ./php83
      dockerfile: Dockerfile
    container_name: php83
    volumes:
      - ../www:/var/www/html
      - ./php83/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql

  node20:
    build:
      context: ./node20
    container_name: node20
    working_dir: /var/www/html
    volumes:
      - ../www:/var/www/html
    tty: true
    stdin_open: true
    ports:
      - "5173:5173"  # Frontend Vite
      - "3000:3000"  # Backend Express

  mysql:
    image: mysql:8.2
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql