FROM node:20

WORKDIR /var/www/html

# Instala dependências úteis
RUN apt-get update && apt-get install -y vim nano git

# Você pode usar o container com:
# docker exec -it node20 bash
# cd nome-do-projeto
# npm create vite@latest .
# ou
# npm init -y && npm install express
